### ISSUE TITLE
Generating difficulties 

### ISSUE THREAD

**Issue by gitvibecheck** [sauravhathi/image-generator-using-openai-api#1]
Hey, I am trying to get your image generator to work, but unfortunately I am having difficulties. The UI runs but nothing happens when I press the button. Unfortunately, I don't have an api.js, as included in the script, either. 

My error messages: 
![grafik](https://user-images.githubusercontent.com/76231530/213913555-47daee67-eee8-4d5c-80af-1a1d0e43c4f1.png)

Thanks a lot for your help!

**Comment by sauravhathi** [comment]
**Link:** https://openai.com/api/

Sign up for an API key and add it to the **api.js** file

1. Create **api.js** file in the root directory and add your API key

` const api = "YOUR_API_KEY";`

**Check updated readme**

Thank you my friend! I'm glad to hear that. :)

**Comment by gitvibecheck** [comment]
Thank you, unfortunately it didn't do much. Do I need to add anything else to the js?

![grafik](https://user-images.githubusercontent.com/76231530/213918663-a62cdc06-011f-497f-91d3-5ca8ce7a9085.png)

**Comment by sauravhathi** [comment]
You have done everything right.
It's totally perfect.

**Comment by gitvibecheck** [comment]
You are right, it's working now!
